name: hungry
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.3.0
  firebase_storage: ^12.2.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/
    - asset/images/
  fonts:
    - family: hungryfont
      fonts:
        - asset: asset\font\Fraunces_9pt_Soft-Regular.ttf
        # If you have multiple font weights or styles, declare them like this:
        - asset: asset\font\Fraunces_9pt_Soft-Bold.ttf
          weight: 700

    


