// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJePBabHkA-zqdJECxney3gAPmd-ccDrI',
    appId: '1:760295982883:web:938642e08901c81183ee96',
    messagingSenderId: '760295982883',
    projectId: 'hungry-dc10f',
    authDomain: 'hungry-dc10f.firebaseapp.com',
    storageBucket: 'hungry-dc10f.appspot.com',
    measurementId: 'G-KJ31H2L8NC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0ga8rsJxYHD6hsU5P9UQ0wVkU_oqjLMY',
    appId: '1:760295982883:android:b8e166529ca81b7c83ee96',
    messagingSenderId: '760295982883',
    projectId: 'hungry-dc10f',
    storageBucket: 'hungry-dc10f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfoQ--q9hTHUWSYAaNOHJTaSln5REKsF8',
    appId: '1:760295982883:ios:76f32f4916675d0383ee96',
    messagingSenderId: '760295982883',
    projectId: 'hungry-dc10f',
    storageBucket: 'hungry-dc10f.appspot.com',
    iosBundleId: 'com.example.hungry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfoQ--q9hTHUWSYAaNOHJTaSln5REKsF8',
    appId: '1:760295982883:ios:76f32f4916675d0383ee96',
    messagingSenderId: '760295982883',
    projectId: 'hungry-dc10f',
    storageBucket: 'hungry-dc10f.appspot.com',
    iosBundleId: 'com.example.hungry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJePBabHkA-zqdJECxney3gAPmd-ccDrI',
    appId: '1:760295982883:web:ecee5262904c534883ee96',
    messagingSenderId: '760295982883',
    projectId: 'hungry-dc10f',
    authDomain: 'hungry-dc10f.firebaseapp.com',
    storageBucket: 'hungry-dc10f.appspot.com',
    measurementId: 'G-GY2CK6PHVS',
  );
}
